[profile.default]
src = "src"
out = "out"
lib = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"

[rpc_endpoints]
predx_local = "http://localhost:8545"
